const CONFIG = {
    
    TEXT: "MARIUS GAL",
    
  
    FONT_SIZE: 80,
    
 
    PARTICLE_SIZE: 2,
    MIN_PARTICLE_SIZE: 0.5,
    PARTICLE_CHANGE_SIZE: 0.8,
    PARTICLE_CHANGE_SPEED: 0.03,
    DENSITY: 3, 
    

    ORBITAL_PARTICLES_COUNT: 500,
    EXPLOSION_PARTICLES: 300,
    CURSOR_PARTICLES_COUNT: 12,
    
 
    ATTRACTION_STRENGTH: 150, 
    FRICTION: 0.97, 
    

    OUTLINE_SEGMENTS: 60 
};